"""add decision_logs table

Revision ID: 17e8dc671db3
Revises: 41e80f1e0c5e
Create Date: 2026-07-01 09:47:11.208892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '17e8dc671db3'
down_revision: Union[str, Sequence[str], None] = '41e80f1e0c5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('decision_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('result_id', sa.UUID(), nullable=False),
    sa.Column('stage', sa.String(length=16), nullable=False),
    sa.Column('decision_type', sa.String(length=48), nullable=False),
    sa.Column('source_phrase', sa.Text(), nullable=True),
    sa.Column('target_phrase', sa.Text(), nullable=True),
    sa.Column('decision', sa.Text(), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=False),
    sa.Column('confidence', sa.String(length=8), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['translation_jobs.id'], ),
    sa.ForeignKeyConstraint(['result_id'], ['translation_results.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_decision_logs_job_id'), 'decision_logs', ['job_id'], unique=False)
    op.create_index(op.f('ix_decision_logs_result_id'), 'decision_logs', ['result_id'], unique=False)
    op.create_index(op.f('ix_decision_logs_stage'), 'decision_logs', ['stage'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_decision_logs_stage'), table_name='decision_logs')
    op.drop_index(op.f('ix_decision_logs_result_id'), table_name='decision_logs')
    op.drop_index(op.f('ix_decision_logs_job_id'), table_name='decision_logs')
    op.drop_table('decision_logs')
    # ### end Alembic commands ###
