"""add glossary entries with pgvector

Revision ID: 41e80f1e0c5e
Revises: 34e486ebe12c
Create Date: 2026-06-18 09:40:51.440183

"""
from typing import Sequence, Union

from alembic import op
import pgvector.sqlalchemy
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '41e80f1e0c5e'
down_revision: Union[str, Sequence[str], None] = '34e486ebe12c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.create_table('glossary_entries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source_term', sa.Text(), nullable=False),
    sa.Column('term_type', sa.String(length=24), nullable=False),
    sa.Column('translations', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('risk_notes', sa.Text(), nullable=True),
    sa.Column('applicable_genres', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('freshness_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_glossary_entries_embedding', 'glossary_entries', ['embedding'], unique=False, postgresql_using='ivfflat', postgresql_ops={'embedding': 'vector_l2_ops'})
    op.create_index(op.f('ix_glossary_entries_source_term'), 'glossary_entries', ['source_term'], unique=False)
    op.create_table('user_glossary_entries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('source_term', sa.Text(), nullable=False),
    sa.Column('term_type', sa.String(length=24), nullable=False),
    sa.Column('translations', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('risk_notes', sa.Text(), nullable=True),
    sa.Column('applicable_genres', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_user_glossary_entries_embedding', 'user_glossary_entries', ['embedding'], unique=False, postgresql_using='ivfflat', postgresql_ops={'embedding': 'vector_l2_ops'})
    op.create_index(op.f('ix_user_glossary_entries_source_term'), 'user_glossary_entries', ['source_term'], unique=False)
    op.create_index(op.f('ix_user_glossary_entries_user_id'), 'user_glossary_entries', ['user_id'], unique=False)
    op.alter_column('translation_jobs', 'target_languages',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('translation_jobs', 'target_languages',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=True)
    op.drop_index(op.f('ix_user_glossary_entries_user_id'), table_name='user_glossary_entries')
    op.drop_index(op.f('ix_user_glossary_entries_source_term'), table_name='user_glossary_entries')
    op.drop_index('ix_user_glossary_entries_embedding', table_name='user_glossary_entries', postgresql_using='ivfflat', postgresql_ops={'embedding': 'vector_l2_ops'})
    op.drop_table('user_glossary_entries')
    op.drop_index(op.f('ix_glossary_entries_source_term'), table_name='glossary_entries')
    op.drop_index('ix_glossary_entries_embedding', table_name='glossary_entries', postgresql_using='ivfflat', postgresql_ops={'embedding': 'vector_l2_ops'})
    op.drop_table('glossary_entries')
    # ### end Alembic commands ###
