"""add acceptance scoring fields

Revision ID: 9e867c377cb5
Revises: 17e8dc671db3
Create Date: 2026-07-01 13:25:42.092875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9e867c377cb5'
down_revision: Union[str, Sequence[str], None] = '17e8dc671db3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('translation_results', sa.Column('acceptance_confidence', sa.Float(), nullable=True))
    op.add_column('translation_results', sa.Column('acceptance_dimensions', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('translation_results', sa.Column('acceptance_sentence_scores', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('translation_results', 'acceptance_sentence_scores')
    op.drop_column('translation_results', 'acceptance_dimensions')
    op.drop_column('translation_results', 'acceptance_confidence')
    # ### end Alembic commands ###
